### ISSUE TITLE
Not best girl

### ISSUE THREAD

**Issue by The60th** [kotooriiii/Village#1]
This discord theme by default does not have a picture of asuna. This is a major problem because as everyone knows asuna is considered best girl.

This could easily be fixed if the developer would just understand asuna best girl, and update the themes sources to correctly reflect this.

**Comment by The60th** [comment]
A fix to this error can be viewed in this repo. 
https://github.com/The60th/Village

**Comment by kotooriiii** [comment]
The theme by default has a beautiful firework display scene but it is able to be changed by changing the URL of the image. :)
